### ISSUE TITLE
Release of Firebase-jobdispatcher

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-jobdispatcher-ios#2]
Hello,

I am a mobile developer and I am curiously watching when firebase-jobdispatcher for iOS arrive.
Could you please let us know when this feature will be available?

Thanks,
Anu

**Comment by morganchen12** [comment]
As far as I know no one is actively working on this. There hasn't been a large amount of community interest, and the job-scheduling needs of iOS apps are very different than those of Android apps.

What use case in particular would you use this library for, if it existed?

**Comment by anuragcm** [comment]
Thanks for response! My use case is when device is attached for charging, I have to trigger a function in my application to perform a task. I thought job dispatcher would be a good option. Do you think that can I achieve this function?

**Comment by morganchen12** [comment]
iOS apps are not allowed to monitor battery state while they're backgrounded, so what you're trying to do may not be possible.

**Comment by ghost** [comment]
Thank You Morgan⁣
